### ISSUE TITLE
pypi name

### ISSUE THREAD

**Issue by nsheff** [staticshock/piper#1]
Hi @staticshock --

With `piper` no longer being maintained, is there any chance you'd be willing to give up the name piper in the pypi index for a new project I'm working on for a python module that I use to build pipelines in python?  You can see more about the project here:

Python module: https://github.com/databio/pypiper

If you'd be willing, it's fairly simple; if you go to this page:

https://pypi.org/manage/project/piper/collaboration/

You should be able to add me as an Owner (my pypi username is also nsheff).

That's all you need to do. That will allow me to clear out the current releases and upload my own, and remove you as the owner as well (I believe). Thanks, I appreciate it!

**Comment by staticshock** [comment]
✅
